In [1]:
import numpy as np

Linear Algebra with Numpy

In [2]:
# 1. Find the rank, trace, determinant and inverse of the matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [3]:
# 2. calculate the eigenvalues
from numpy import linalg as geek
 
# Creating an array using array 
# function
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :",a)
 
# calculating an eigen value
# using eigh() function
c, d = geek.eigh(a)
 
print("Eigen value is :", c)
print("Eigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is : [0.17157288 5.82842712]
Eigen value is : [[-0.92387953-0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [4]:
# 3. function to compute the eigenvalues and right eigenvectors of a square array.
# Creating an array using diag  function
a = np.diag((1, 2, 3))
 
print("Array is :",a)
 
# calculating an eigen value using eig() function
c, d = geek.eig(a)
 
print("Eigen value is :",c)
print("Eigen value is :",d)

Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigen value is : [1. 2. 3.]
Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 4.Python Program to solve a given linear equation
 
import numpy as np
 
# Creating an array using array function
a = np.array([[1, 2], [3, 4]])
 
# Creating an array using array function
b = np.array([8, 18])
 
print(("Solution of linear equations:", 
      np.linalg.solve(a, b)))

('Solution of linear equations:', array([2., 3.]))


Using Numpy arrays

In [6]:
# 1. Creating a numpy array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# 2. Array creation using numpy methods 
b = np.empty(2, dtype = int)
print("Matrix b : \n", b)
 
a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [         1 1074266112]

Matrix a : 
 [[        -3 1073741823]
 [         1 1074266112]]

Matrix c : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# 3. Returns an array with evenly spaced elements as per the interval
print("A\n", np.arange(4).reshape(2, 2), "\n")
 
print("A\n", np.arange(4, 10), "\n")
 
print("A\n", np.arange(4, 20, 3), "\n")


A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [9]:
# 4. Returns number spaces evenly w.r.t interval. Similiar to arange but instead of step it uses sample number.
# restep set to True
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range 
x = np.linspace(0, 2, 10)
print("A\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [10]:
# 5. copy of array collapsed into one dimension
# Python Program illustrating numpy.flatten() method
 
 
array = np.array([[1, 2], [3, 4]])
 
# using flatten method
array.flatten()
print(array)
 
#using fatten method 
array.flatten('F')
print(array)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Vectorized operations

In [11]:
# 1.
# importing the modules
import timeit

# vectorized sum
print(np.sum(np.arange(15000)))

print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))

# itersative sum
total = 0
for item in range(0, 15000):
	total += item
a = total
print("\n" + str(a))

print("Time taken by iterative sum : ", end = "")
%timeit a


112492500
Time taken by vectorized sum : 55.5 µs ± 2.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

112492500
Time taken by iterative sum : 76.9 ns ± 2.72 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
# 2.
# importing the modules
import numpy as np
import timeit
import math

# vectorized operation
print("Time taken by vectorized operation : ", end = "")
%timeit np.exp(np.arange(150))

# non-vectorized operation
print("Time taken by non-vectorized operation : ", end = "")
%timeit [math.exp(item) for item in range(150)]


Time taken by vectorized operation : 9.23 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Time taken by non-vectorized operation : 79.3 µs ± 19.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Universal functions

In [13]:
# 1.
# Python code to demonstrate trignometric function
import numpy as np

# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)

# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

# hyperbolic sine of angles
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))

# inverse sine hyperbolic
print('Inverse Sine hyperbolic:')
print(np.sin(sineh_value))

# hypot function demonstration
base = 4
height = 3
print('hypotenuse of right triangle is:')
print(np.hypot(base, height))


Sine of angles in the array:
[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
Inverse Sine of sine values:
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
Sine hyperbolic of angles in the array:
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
Inverse Sine hyperbolic:
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
hypotenuse of right triangle is:
5.0


In [14]:
# 2.
# Python code demonstrate statistical function
import numpy as np

# construct a weight array
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# minimum and maximum
print('Minimum and maximum weight of the students: ')
print(np.amin(weight), np.amax(weight))

# range of weight i.e. max weight-min weight
print('Range of the weight of the students: ')
print(np.ptp(weight))

# percentile
print('Weight below which 70 % student fall: ')
print(np.percentile(weight, 70))

# mean
print('Mean weight of the students: ')
print(np.mean(weight))

# median
print('Median weight of the students: ')
print(np.median(weight))

# standard deviation
print('Standard deviation of weight of the students: ')
print(np.std(weight))

# variance
print('Variance of weight of the students: ')
print(np.var(weight))

# average
print('Average weight of the students: ')
print(np.average(weight))


Minimum and maximum weight of the students: 
45.0 73.25
Range of the weight of the students: 
28.25
Weight below which 70 % student fall: 
55.317
Mean weight of the students: 
54.3225
Median weight of the students: 
51.6
Standard deviation of weight of the students: 
8.052773978574091
Variance of weight of the students: 
64.84716875
Average weight of the students: 
54.3225


In [15]:
# 3. 
# Python code to demonstrate bitwise-function
import numpy as np

# construct an array of even and odd numbers
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

# bitwise_and
print('bitwise_and of two arrays: ')
print(np.bitwise_and(even, odd))

# bitwise_or
print('bitwise_or of two arrays: ')
print(np.bitwise_or(even, odd))

# bitwise_xor
print('bitwise_xor of two arrays: ')
print(np.bitwise_xor(even, odd))

# invert or not
print('inversion of even no. array: ')
print(np.invert(even))

# left_shift
print('left_shift of even no. array: ')
print(np.left_shift(even, 1))

# right_shift
print('right_shift of even no. array: ')
print(np.right_shift(even, 1))


bitwise_and of two arrays: 
[ 0  2  4  6  8 16 32]
bitwise_or of two arrays: 
[ 1  3  5  7  9 17 33]
bitwise_xor of two arrays: 
[1 1 1 1 1 1 1]
inversion of even no. array: 
[ -1  -3  -5  -7  -9 -17 -33]
left_shift of even no. array: 
[ 0  4  8 12 16 32 64]
right_shift of even no. array: 
[ 0  1  2  3  4  8 16]


Broadcasting and shape manipulation

In [16]:
# 1. Single Dimension array
import numpy as np
a = np.array([17, 11, 19]) # 1x3 Dimension array
print(a)
b = 3
print(b)

# Broadcasting happened because of
# miss match in array Dimension.
c = a + b
print(c)


[17 11 19]
3
[20 14 22]


In [17]:
# 2. two Dimension array
import numpy as np
A = np.array([[11, 22, 33], [10, 20, 30]])
print(A)

b = 4
print(b)

C = A + b
print(C)


[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


In [19]:
# 3.
import numpy as np

v = np.array([12, 24, 36])
w = np.array([45, 55])

# To compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])

# x has shape 2x3 and v has shape (3, )
# so they broadcast to 2x3,
print(X + v)

# Add a vector to each column of a matrix X has
# shape 2x3 and w has shape (2, ) If we transpose X
# then it has shape 3x2 and can be broadcast against w
# to yield a result of shape 3x2.

# Transposing this yields the final result
# of shape 2x3 which is the matrix.
print((X.T + w).T)

# Another solution is to reshape w to be a column
# vector of shape 2X1 we can then broadcast it
# directly against X to produce the same output.
print(X + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant, X has shape 2x3.
# Numpy treats scalars as arrays of shape();
# these can be broadcast together to shape 2x3.
print(X * 2)


[[ 540  660]
 [1080 1320]
 [1620 1980]]
[[ 24  46  69]
 [ 57  79 102]]
[[ 57  67  78]
 [100 110 121]]
[[ 57  67  78]
 [100 110 121]]
[[ 24  44  66]
 [ 90 110 132]]


In [20]:
# 4. reshape an array
x = np.array([[2,3,4], [5,6,7]])      
np.reshape(x, (3, 2))

array([[2, 3],
       [4, 5],
       [6, 7]])

Boolean mask

In [21]:
# 1.
B = np.array([[42,56,89,65],
              [99,88,42,12],
              [55,42,17,18]])

print(B>=42)

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True False False]]


In [22]:
# 2.
import numpy as np

A = np.array([4, 7, 3, 4, 2, 8])

print(A == 4)

[ True False False  True False False]


In [23]:
# 3. 
import numpy as np

A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])

B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

Date and Time in Numpy

In [24]:
# using numpy.datetime64() method
dt = np.array(np.datetime64('2019-08-26'))

print(dt)


2019-08-26
