In [1]:
# 1.
from scipy import stats

arr1 = [9, 3, 27]

desc = stats.describe(arr1)

print("No. of observations is :\n", desc)


No. of observations is :
 DescribeResult(nobs=3, minmax=(3, 27), mean=13.0, variance=156.0, skewness=0.5280049792181878, kurtosis=-1.5)


In [2]:
# 2. FInding statistics of data

from scipy import stats

arr1 = [[1, 3, 27],[3, 4, 6],[7, 6, 3],[3, 6, 8]]

desc = stats.describe(arr1, axis = 0)


print("No. of observations at axis = 0 :\n\n", desc)


print("\n\nNo. of observations at axis = 1 :\n\n", desc)


No. of observations at axis = 0 :

 DescribeResult(nobs=4, minmax=(array([1, 3, 3]), array([ 7,  6, 27])), mean=array([ 3.5 ,  4.75, 11.  ]), variance=array([  6.33333333,   2.25      , 118.        ]), skewness=array([ 0.65202366, -0.21383343,  1.03055786]), kurtosis=array([-0.90304709, -1.72016461, -0.75485971]))


No. of observations at axis = 1 :

 DescribeResult(nobs=4, minmax=(array([1, 3, 3]), array([ 7,  6, 27])), mean=array([ 3.5 ,  4.75, 11.  ]), variance=array([  6.33333333,   2.25      , 118.        ]), skewness=array([ 0.65202366, -0.21383343,  1.03055786]), kurtosis=array([-0.90304709, -1.72016461, -0.75485971]))


Linear Algrbra

In [3]:
# 1.
# Import the required libraries
from scipy import linalg
import numpy as np

# The function takes two arrays
a = np.array([[7, 2], [4, 5]])
b = np.array([8, 10])

# Solving the linear equations
res = linalg.solve(a, b)
print(res)


[0.74074074 1.40740741]


In [4]:
# 2.
# Initializing the matrix
x = np.array([[7, 2], [4, 5]])

# Finding the inverse of matrix x
y = linalg.inv(x)
print(y)


[[ 0.18518519 -0.07407407]
 [-0.14814815  0.25925926]]


In [5]:
# 3. 
# Initializing the matrix A
A = np.array([[9 , 6] , [4 , 5]])

# Finding the determinant of matrix A
D = linalg.det(A)
print(D)


21.0


In [6]:
# 4. singular value decomposition

# Initializing the matrix M
M = np.array([[1 , 5] , [6 , 10]])

# Passing the values to the
# eigen function
x , y , z = linalg.svd(M)
print(x , y , z)



[[-0.38684104 -0.92214641]
 [-0.92214641  0.38684104]] [12.62901571  1.58365469] [[-0.46873958 -0.88333641]
 [ 0.88333641 -0.46873958]]


In [7]:
# 5.
# Initializing the matrix M
M = np.array([[9 , 3] , [2 , 4]])

# Passing the values to the eigen
# function
val , vect = linalg.eig(M)

# Display the Eigen values and Eigen
# vectors
print(val)
print(vect)


[10.+0.j  3.+0.j]
[[ 0.9486833  -0.4472136 ]
 [ 0.31622777  0.89442719]]


In [8]:
# 6.
# Initializing the input array 
x = np.array([6 , 3])
  
# Calculating the L2 norm
a = linalg.norm(x)
  
# Calculating the L1 norm
b = linalg.norm(x , 1)
  
# Displaying the norm values
print(a)
print(b)

6.708203932499369
9.0


In [9]:
# 7. 
# Initializing the matrix
x = np.array([[16 , 4] , [100 , 25]])

# Calculate and print the matrix square root
r = linalg.sqrtm(x)
print(r)
print("\n")

# Calculate and print the matrix exponential
e = linalg.expm(x)
print(e)
print("\n")

# Calculate and print the matrix sine
s = linalg.sinm(x)
print(s)
print("\n")

# Calculate and print the matrix cosine
c = linalg.cosm(x)
print(c)
print("\n")

# Calculate and print the matrix tangent
t = linalg.tanm(x)
print(t)


[[ 2.49878019  0.62469505]
 [15.61737619  3.90434405]]


[[2.49695022e+17 6.24237555e+16]
 [1.56059389e+18 3.90148472e+17]]


[[-0.06190153 -0.01547538]
 [-0.38688456 -0.09672114]]


[[ 0.22445296 -0.19388676]
 [-4.84716897 -0.21179224]]


[[0.0626953  0.01567382]
 [0.39184561 0.0979614 ]]



Data Analysis with SciPy

In [10]:
# 1.
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)
# print LU decomposition
print(np.dot(L,U))


[[1. 0.]
 [0. 1.]]
[[1.         0.        ]
 [0.44444444 1.        ]]
[[9.         6.        ]
 [0.         2.33333333]]
[[9. 6.]
 [4. 5.]]


In [11]:
# 2.
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)


[12.29150262+0.j  1.70849738+0.j]
[[ 0.8767397  -0.6354064 ]
 [ 0.48096517  0.7721779 ]]


In [13]:
# 3.
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
v = np.array([[2],[3],[5]])
print(v)
s = linalg.solve(A,v)
print(s)


[[2]
 [3]
 [5]]
[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


In [14]:
# 4.
import scipy.integrate
f= lambda x:np.exp(-x**2)
# print results
i = scipy.integrate.quad(f, 0, 1)
print(i)


(0.7468241328124271, 8.291413475940725e-15)
